Bring POM / names in line with booster rules
snowdrop/spring-boot-istio-routing-booster pull request #3
Opened 2018-04-26 17:42 UTC by lincolnthree

2018-04-27 06:13 UTC, geoand approved these changes
LGTM but it's of course difficult to tell without actually testing :)

2018-04-27 10:42 UTC, metacosm requested changes

2018-04-27 10:42 UTC, metacosm commented on pom.xml
>  		<fabric8-maven-plugin.version>3.5.34</fabric8-maven-plugin.version>
This should be removed along with the 2 next lines if I'm not mistaken.

2018-04-27 10:54 UTC, geoand commented on pom.xml
>  		<fabric8-maven-plugin.version>3.5.34</fabric8-maven-plugin.version>
Unless Github is showing the wrong lines, why would the `artifactId`, `version` and `packaging` tags need to be removed?

2018-04-27 11:01 UTC, metacosm commented on pom.xml
>  		<fabric8-maven-plugin.version>3.5.34</fabric8-maven-plugin.version>
The comment applies to line 19-21 (and shows properly in here). It just that the comment doesn't apply to a change so it's not highlighted :)

2018-04-27 11:06 UTC, geoand commented on pom.xml
>  		<fabric8-maven-plugin.version>3.5.34</fabric8-maven-plugin.version>
Thanks! That makes it clear :)

2018-04-27 18:49 UTC, lincolnthree commented
Please review.

2018-04-30 08:29 UTC, metacosm approved these changes
LGTM (albeit without testing).

2018-05-11 15:25 UTC, closed without merging